version: '3.3'
services:
  node0:
    build: .
    ports:
      - '9090:9090'
    environment:
      PID: 0
      initiates: 1
    volumes:
      - type: bind
        source: ./logs/node0
        target: /log
  node1:
    build: .
    ports:
      - '9091:9091'
    environment:
      PID: 1
      initiates: 1
    volumes:
      - type: bind
        source: ./logs/node1
        target: /log
  node2:
    build: .
    ports:
      - '9092:9092'
    environment:
      PID: 2
      initiates: 1
    volumes:
      - type: bind
        source: ./logs/node2
        target: /log
  node3:
    build: .
    ports:
      - '9093:9093'
    environment:
      PID: 3
      initiates: 1
    volumes:
      - type: bind
        source: ./logs/node3
        target: /log
  node4:
    build: .
    ports:
      - '9094:9094'
    environment:
      PID: 4
      initiates: 1
    volumes:
      - type: bind
        source: ./logs/node4
        target: /log
  node5:
    build: .
    ports:
      - '9095:9095'
    environment:
      PID: 5
      initiates: 1
    volumes:
      - type: bind
        source: ./logs/node5
        target: /log
  node6:
    build: .
    ports:
      - '9096:9096'
    environment:
      PID: 6
      initiates: 1
    volumes:
      - type: bind
        source: ./logs/node6
        target: /log
  node7:
    build: .
    ports:
      - '9097:9097'
    environment:
      PID: 7
      initiates: 1
    volumes:
      - type: bind
        source: ./logs/node7
        target: /log
  node8:
    build: .
    ports:
      - '9098:9098'
    environment:
      PID: 8
      initiates: 1
    volumes:
      - type: bind
        source: ./logs/node8
        target: /log
  node9:
    build: .
    ports:
      - '9099:9099'
    environment:
      PID: 9
      initiates: 1
    volumes:
      - type: bind
        source: ./logs/node9
        target: /log